//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileFormat.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileFormat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LOGFILE
        ///DEFAULT
        ///END-LOGFILE
        ///LIMITS
        ///  MINIMUM-TASKS=1
        ///  MAXIMUM-TASKS=100
        ///  MINIMUM-PROCESSORS=1
        ///  MAXIMUM-PROCESSORS=500
        ///  MINIMUM-PROCESSOR-FREQUENCIES=1.37
        ///  MAXIMUM-PROCESSOR-FREQUENCIES=10.0
        ///  MINIMUM-RAM=1
        ///  MAXIMUM-RAM=64
        ///  MINIMUM-DOWNLOAD=1
        ///  MAXIMUM-DOWNLOAD=1000
        ///  MINIMUM-UPLOAD=1
        ///  MAXIMUM-UPLOAD=1000
        ///END-LIMITS
        ///PROGRAM
        ///  DURATION=3.0
        ///  TASKS=5
        ///  PROCESSORS=3
        ///END-PROGRAM
        ///TASKS
        ///  TASK
        ///    ID=0
        ///    RUNTIME=1.0
        ///    REFERENCE-FREQUENCY=2.2
        ///    RAM=2
        ///    DOWNLOAD=100
        ///    U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CFFKeyWords
        {
            get
            {
                return ResourceManager.GetString("CFFKeyWords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONFIGURATION-DATA 
        ///  FILENAME=&quot;PT1 - Test1.cff&quot;
        ///END-CONFIGURATION-DATA
        ///ALLOCATIONS
        ///  COUNT=2
        ///  TASKS=5
        ///  PROCESSORS=3
        ///  ALLOCATION
        ///    ID=0
        ///    MAP=1,1,0,0,0
        ///  END-ALLOCATION
        ///END-ALLOCATIONS.
        /// </summary>
        internal static string TFFKeyWords
        {
            get
            {
                return ResourceManager.GetString("TFFKeyWords", resourceCulture);
            }
        }
    }
}
